ShopBundle\Entity\OrderItems:
    exclusion_policy: ALL
    properties:
        discount:
            expose: true
        amount:
            expose: true
        products:
            expose: true
        cost:
            expose: true