<?php

namespace ShopBundle\Repository;

/**
 * BrandsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandsRepository extends \Doctrine\ORM\EntityRepository
{
}
