<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartItemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemsRepository extends EntityRepository
{
}
