<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * delivery_typeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class delivery_typeRepository extends EntityRepository
{
}
