<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdersInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdersInfoRepository extends EntityRepository
{
}
