<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * order_infoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class order_infoRepository extends EntityRepository
{
}
