<?php

namespace ShopBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * rolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rolesRepository extends EntityRepository
{
}
