<?php

namespace Login\LoginBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RolesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RolesRepository extends EntityRepository
{
}
