cart_add:
    path:     /add
    defaults: { _controller: "ShopBundle:Cart:add" }
cart_index:
    path:     /index
    defaults: { _controller: "ShopBundle:Cart:index" }
cart_delete:
    path:     /delete/{id}
    defaults: { _controller: "ShopBundle:Cart:delete" }