cart_index:
    path:     /index
    defaults: { _controller: "ShopBundle:Cart:index" }
    options:
                        breadcrumb:
                            label: 'My Cart'
                            parent_route: products_index
cart_add:
    path:     /add
    defaults: { _controller: "ShopBundle:Cart:add" }
cart_delete:
    path:     /delete/{id}
    defaults: { _controller: "ShopBundle:Cart:delete" }