products_index:
    path:     /
    defaults: { _controller: "ShopBundle:Products:index" }
    methods:  GET

products_category:
    path:     /{slug}
    defaults: { _controller: "ShopBundle:Products:showCategory" }
    methods:  GET

products_show:
    path:     /{slug2}/{slug}
    defaults: { _controller: "ShopBundle:Products:showSingle" }
    methods:  GET