products_index:
    path:     /
    defaults: { _controller: "ShopBundle:Products:index" }
    methods:  GET
products_show:
    path:     /{id}
    defaults: { _controller: "ShopBundle:Products:show" }
    methods:  GET