shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_contact:
    path:     /contact
    defaults: { _controller: ShopBundle:Contact:contactVendor }

shop_products:
    resource: "@ShopBundle/Resources/config/routing/products.yml"
    prefix:   /products

shop_about:
    path:     /about_us
    defaults: { _controller: ShopBundle:About:about }

shop_wishlist:
    path:     /wishlist
    defaults: { _controller: ShopBundle:Wishlist:wishlist }

shop_wishlist_add:
    path:     /wishlist/add-to-wishlist
    defaults: { _controller: ShopBundle:Wishlist:addWishlistProduct }

shop_wishlist_delete:
    path:     /wishlist/delete-from-wishlist
    defaults: { _controller: ShopBundle:Wishlist:deleteFromWishlist }

shop_cart:
    resource: "@ShopBundle/Resources/config/routing/cart.yml"
    prefix:   /cart

api:
    path:     /api/orders
    defaults: { _controller: ShopBundle:apiOrders:getOrders }

api_count:
    path:     /api/set-count
    defaults: { _controller: ShopBundle:apiOrders:setCount}

api_order_status:
    path:     /api/set-order-status
    defaults: { _controller: ShopBundle:apiOrders:setOrderStatus}


api_products:
    path:     /api/get-products
    defaults: { _controller: ShopBundle:Products:addProduct}

shop_checkout:
    resource: "@ShopBundle/Resources/config/routing/checkout.yml"
    prefix:   /checkout
shop_login:
    path:     /login
    defaults: { _controller: SonataUserBundle:SecurityFOSUser1:login }
