shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }
contact_vendor:
    path:     /vendor-contact
    defaults: { _controller: ShopBundle:Default:contactVendor }

shop_categories:
    resource: "@ShopBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

product-single:
    resource: "@ShopBundle/Resources/config/routing/single-product.yml"
    prefix:   /single-product

about_us:
    path:     /about
    defaults: { _controller: ShopBundle:Default:about }
