shop_homepage:
    path:     /
    defaults: { _controller: ShopBundle:Default:index }

shop_contact:
    path:     /contact
    defaults: { _controller: ShopBundle:Contact:contactVendor }

shop_products:
    resource: "@ShopBundle/Resources/config/routing/products.yml"
    prefix:   /products

shop_about:
    path:     /about_us
    defaults: { _controller: ShopBundle:About:about }

shop_wishlist:
    path:     /wishlist
    defaults: { _controller: ShopBundle:Wishlist:wishlist }


shop_cart:
    resource: "@ShopBundle/Resources/config/routing/cart.yml"
    prefix:   /cart

shop_checkout:
    resource: "@ShopBundle/Resources/config/routing/checkout.yml"
    prefix:   /checkout

