services:
#    shop.example:
#        class: ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.admin.categories:
        class: ShopBundle\Admin\CategoriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - ShopBundle\Entity\Categories
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.images:
        class: ShopBundle\Admin\ImagesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Images" }
        arguments:
            - ~
            - ShopBundle\Entity\Images
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.products:
        class: ShopBundle\Admin\ProductsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Products" }
        arguments:
            - ~
            - ShopBundle\Entity\Products
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.feedback:
        class: ShopBundle\Admin\FeedbackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Feedback" }
        arguments:
            - ~
            - ShopBundle\Entity\Feedback
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.orders_info:
        class: ShopBundle\Admin\OrderInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Orders Info" }
        arguments:
            - ~
            - ShopBundle\Entity\OrdersInfo
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true