services:
#    shop.example:
#        class: ShopBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    app.admin.brands:
        class: ShopBundle\Admin\BrandsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Brands" }
        arguments:
            - ~
            - ShopBundle\Entity\Brands
            - ~
    app.admin.categories:
        class: ShopBundle\Admin\CategoriesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Categories" }
        arguments:
            - ~
            - ShopBundle\Entity\Categories
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.images:
        class: ShopBundle\Admin\ImagesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Images", show_in_dashboard: false }
        arguments:
            - ~
            - ShopBundle\Entity\Images
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.products:
        class: ShopBundle\Admin\ProductsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Products" }
        arguments:
            - ~
            - ShopBundle\Entity\Products
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.feedback:
        class: ShopBundle\Admin\FeedbackAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Feedback" }
        arguments:
            - ~
            - ShopBundle\Entity\Feedback
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.orders_info:
        class: ShopBundle\Admin\OrderInfoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Orders Info" }
        arguments:
            - ~
            - ShopBundle\Entity\OrdersInfo
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.order_items:
        class: ShopBundle\Admin\OrderItemsAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Order Items" }
        arguments:
            - ~
            - ShopBundle\Entity\OrderItems
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.delivery_type:
        class: ShopBundle\Admin\DeliveryTypeAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Delivery Type" }
        arguments:
            - ~
            - ShopBundle\Entity\DeliveryType
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.pages:
        class: ShopBundle\Admin\PagesAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Pages" }
        arguments:
            - ~
            - ShopBundle\Entity\Pages
            - ~
#        calls:
#            - [ setTranslationDomain, [ShopBundle]]
        public: true
    app.admin.wishlist:
        class: ShopBundle\Admin\WishlistAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Wishlist" }
        arguments:
            - ~
            - ShopBundle\Entity\Wishlist
            - ~

    shop.categories_view_model_assembler:
                class: ShopBundle\ViewModels\Product\CategoriesViewModelAssembler
                parent: gotakk.view_model.view_model_assembler
    shop.product_view_model_assembler:
                    class: ShopBundle\ViewModels\Product\ProductViewModelAssembler
                    parent: gotakk.view_model.view_model_assembler
    shop.relprod_view_model_assembler:
                        class: ShopBundle\ViewModels\Product\RelProductVievModelAssembler
                        parent: gotakk.view_model.view_model_assembler
    shop.index_view_model_assembler:
                            class: ShopBundle\ViewModels\Index\IndexViewModelAssembler
                            parent: gotakk.view_model.view_model_assembler

    twig.extension.getFooterCategories:
        class: ShopBundle\Services\Twig\GetCategories
        arguments: ['@doctrine.orm.default_entity_manager', '@security.context']
        tags:
            - { name: twig.extension }
            - { name: security.context }