<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;
use Sonata\UserBundle\Entity\BaseUser;


/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }

    public function addRole($role)
    { $role = strtoupper($role);

        if (!in_array($role, $this->roles, true)) {
            $this->roles[] = $role;
        }

        return $this;
    }
    public function __construct()
    {
        parent::__construct();
        $this->roles = array('ROLE_USER');

        $this->setUpdatedToken(new \DateTime());
        $source = uniqid(uniqid(mt_rand(0, PHP_INT_MAX), true), true);
        for ($t=0; $t<64; $t++) {
            $source .= chr((mt_rand() ^ mt_rand()) % 256);
        }
        $token = sha1(hash('sha512', $source, true));
        $this->setToken($token);
    }


    /**
     * @var \DateTime
     */
    protected $updatedToken;
    /**
     * @return \DateTime
     */
    public function getUpdatedToken(): \DateTime
    {
        return new \DateTime();
    }
    /**
     * @param \DateTime $updatedToken
     */
    public function setUpdatedToken(\DateTime $updatedToken)
    {
        $this->updatedToken = $updatedToken;
    }



    protected $username;

    /**
     * @return mixed
     */
    public function getUsername()
    {
        return $this->username;
    }

    /**
     * @param mixed $username
     */
    public function setUsername($username)
    {
        $this->username = $username;
    }

    /**
     * @return string
     */
    public function getSalt()
    {
        return $this->salt;
    }

    /**
     * @param string $salt
     */
    public function setSalt($salt)
    {
        $this->salt = $salt;
    }





}
